name: Security audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rustsec/audit-check@v1.4.1
        with:
          ignore: "RUSTSEC-2022-0093"
          token: ${{ secrets.GITHUB_TOKEN }}